### ISSUE TITLE
Get rid of React

### ISSUE THREAD

**Issue by KOLANICH** [FredrikAugust/bulk-renamer#2]

**Comment by FredrikAugust** [comment]
Why?

**Comment by KOLANICH** [comment]
Because of different things:
1. frameworks like React are usually unneeded, especially in simple apps; VanillaJS should result in less overhead;
2. they are dependencies;
3. the code in the current state looks like it needs compilation (why does it have `js` extension rather than `jsx`? `js` files are for JavaScript, `jsx` ones are for JS with React extensions), and compilation is an additional step requiring one to have access to the compiler. Having access to the compiler usually means that one has to use Node and NPM shit.

**Comment by FredrikAugust** [comment]
I agree that it is not strictly necessary, but I do not see the harm of having it here. It works just fine with, and as the target audience is hackers/developers, I don't believe the performance impact is significant enough to warrant a change.

If you would like to rewrite this without react, feel free, but I won't spend my time on it.

As for the `js`/`jsx` discussion; `create-react-app` creates `.js`-files, and I simply couldn't be bothered to change it.

Thank you for the criticism though :)
